import { Vehicle } from '@/types/vehicle';

/**
 * Real inventory data scraped from jsautohaus.com
 * Last updated: 2026-02-10
 * Source: https://jsautohaus.com/inventory
 */

function generateSlug(year: number, make: string, model: string, trim?: string): string {
  const parts = [year, make, model, trim].filter(Boolean);
  return parts.join('-').toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-');
}

const now = new Date().toISOString();

export const realInventory: Vehicle[] = [
  {
    id: 'ZFF97CMA6N0278496',
    slug: generateSlug(2022, 'Ferrari', '812-GTS'),
    year: 2022,
    make: 'Ferrari',
    model: '812 GTS',
    trim: 'Base',
    price: 549995,
    mileage: 4489,
    stock: '25897',
    vin: 'ZFF97CMA6N0278496',
    bodyType: 'Convertible',
    condition: 'used',
    engine: 'V12',
    transmission: '7-Speed Manual',
    drivetrain: 'RWD',
    fuelType: 'Gasoline',
    mpgCity: 12,
    mpgHighway: 15,
    exteriorColor: 'Nero',
    interiorColor: 'Blue',
    doors: 2,
    description: '2022 Ferrari 812 GTS Nero RWD 7-Speed Manual V12. Clean CARFAX.',
    features: ['Keyless Entry'],
    images: [
      'https://images.app.ridemotive.com/azqlv9zjapur7j0ni3btfh21euvn',
      'https://images.app.ridemotive.com/u6gxk42jf5u6fshaact9uxb1w92h',
      'https://images.app.ridemotive.com/o76puiv40gfon5a9590m4ksqnvik',
      'https://images.app.ridemotive.com/ysnwhxllsgul72n0e3e3yoc9hp4z',
      'https://images.app.ridemotive.com/ck1bfmejdd3690bwohq5qhy0xo8d',
      'https://images.app.ridemotive.com/iml93xxsehq77nbojh0dykre227m',
      'https://images.app.ridemotive.com/6mro8qn64c6rl0yf98bc7bqz12kt',
      'https://images.app.ridemotive.com/uqdtjtk2h6de6e165vydo35mljhu',
      'https://images.app.ridemotive.com/c9rn1z4bf3kzqcx7kabwyfj7jlk0',
      'https://images.app.ridemotive.com/26p5dobbd86bmfw78s74hufzzofc',
      'https://images.app.ridemotive.com/rdl3vg9fooupw7y1doncnxbylf7r',
      'https://images.app.ridemotive.com/52imeh0zv1h5dudi0wtcmlknt3j4',
      'https://images.app.ridemotive.com/8rlix6va4cx2vwz6q9u9zhluzqs2',
      'https://images.app.ridemotive.com/zyaenz4y3f9gfeqwzm34y8plwl88',
      'https://images.app.ridemotive.com/2s9c0jvyrkyqhx57lrj7qm216znn',
      'https://images.app.ridemotive.com/kinadv9faoxm3hncvxvqg7uyepxe',
      'https://images.app.ridemotive.com/l3znng8valvy6hvgej310fflyx7f',
      'https://images.app.ridemotive.com/i0qcfw2l1o96s8la81kql35pd9dh',
      'https://images.app.ridemotive.com/gt4grojjaxy1hd8otfb51ime5vy6',
      'https://images.app.ridemotive.com/voqh7yxe1f2k9r2ucsx08nzlomlw',
      'https://images.app.ridemotive.com/z67gcda13idjk5ifgwuvw1ie3jeu',
      'https://images.app.ridemotive.com/sxovwpm6y8dm8783gg5y650ikn7q',
      'https://images.app.ridemotive.com/2whukvs9dn6wavght1bmhpest204',
      'https://images.app.ridemotive.com/pqitlqqxhqfg4w29zycminemknbe',
      'https://images.app.ridemotive.com/dl5suj1v6y6mchy7g8cntwl1o1n4',
      'https://images.app.ridemotive.com/ehu55uyt30dtuhodwb4lsfbekvx9',
      'https://images.app.ridemotive.com/ortkojqgfso2t93i2vpfctd155go',
      'https://images.app.ridemotive.com/xrvff5ecbnyipkodrtlvbk36rl7i',
      'https://images.app.ridemotive.com/slh7m8lq3wvp90olvr8y6l7eyq0n',
      'https://images.app.ridemotive.com/f87muwytirzg8zobj483qs1ek98r',
      'https://images.app.ridemotive.com/3gv4pny0mrs5mfz5rn2ucp8apzux',
      'https://images.app.ridemotive.com/74aqj9la9rfjytslmjc3jru6uim1',
      'https://images.app.ridemotive.com/kfocnxlanbwrzpqm2aqmgc44tgfd',
      'https://images.app.ridemotive.com/de1euzk73lpd0iz3lm0dfpik0li9',
      'https://images.app.ridemotive.com/owgnpc29uzisd7l7yyfzfypradi8',
      'https://images.app.ridemotive.com/tlwloxz35g6igehpz2izfs2b88u9',
      'https://images.app.ridemotive.com/7gdmjxewa5irhd6izhictbvwocgh',
      'https://images.app.ridemotive.com/nxipopuwz8h1nd20vf8x6vqb8vbo',
      'https://images.app.ridemotive.com/9mgsrjgls2ypacd6o6c92jzdiwd3',
      'https://images.app.ridemotive.com/r88057f66ger62npfdyhxa0n81c9',
      'https://images.app.ridemotive.com/4l6ij0noeofkav246icwyesgf08l',
      'https://images.app.ridemotive.com/pzqlpjdixbsuihg6robzed5i906c',
      'https://images.app.ridemotive.com/25c4j4mmr6y6j260ttfe45t4rw1w'
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/azqlv9zjapur7j0ni3btfh21euvn',
    carfaxUrl: 'https://www.carfax.com/vehiclehistory/ar20/rn5ksyPtyYrsEhezs9kHix2X7EVvISTn14UsAXlPQAie1iYFSnJEeKa0LUlzSOEtimiO58jzmTeZKRnzOYhCIfmMIXT0Mie5DAQ',
    detailUrl: '/inventory/Used-2022-Ferrari-812_GTS-Base-ZFF97CMA6N0278496',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'WP0AE2A98JS185810',
    slug: generateSlug(2018, 'Porsche', '911-GT2-RS'),
    year: 2018,
    make: 'Porsche',
    model: '911',
    trim: 'GT2 RS',
    price: 549995,
    mileage: 5100,
    stock: '25191',
    vin: 'WP0AE2A98JS185810',
    bodyType: 'Coupe',
    condition: 'used',
    engine: '3.8L H6 Turbocharged DOHC 24V LEV3-LEV160 700hp',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    fuelType: 'Gasoline',
    mpgCity: 15,
    mpgHighway: 20,
    exteriorColor: 'White',
    interiorColor: 'Black',
    doors: 2,
    description: '2018 Porsche 911 GT2 RS. Clean CARFAX.',
    features: ['Keyless Entry', 'Turbocharged'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
      'https://images.app.ridemotive.com/ubv5a4tzl0wcvxhb3jh7q7ob7flt',
      'https://images.app.ridemotive.com/lt9u5f3qcir2jns1yk90fuarsh8d',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com/vehiclehistory/ar20/wcuIhtlbc1-gp5kuVlDTWTk6IjfwdjlEJYRa6bCSp8hDNp2cdgjyZ7TgyRVmVMrhK361CpL6IZqUxCBkoe8L6S7KgQ8f-SEOb9k',
    detailUrl: '/inventory/Used-2018-Porsche-911-GT2_RS-WP0AE2A98JS185810',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ZFF95NLA0P0292593',
    slug: generateSlug(2023, 'Ferrari', 'SF90-Stradale'),
    year: 2023,
    make: 'Ferrari',
    model: 'SF90 Stradale',
    trim: 'Base',
    price: 439995,
    mileage: 3900,
    stock: '25077',
    vin: 'ZFF95NLA0P0292593',
    bodyType: 'Coupe',
    condition: 'used',
    engine: 'V8',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    fuelType: 'Gasoline',
    mpgCity: 15,
    mpgHighway: 18,
    exteriorColor: 'Red',
    interiorColor: 'Black',
    doors: 2,
    description: '2023 Ferrari SF90 Stradale. Clean CARFAX.',
    features: ['Keyless Entry', 'AWD'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
      'https://images.app.ridemotive.com/ubv5a4tzl0wcvxhb3jh7q7ob7flt',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com/vehiclehistory/ar20/vr_7THOtdMP9CKfebKL4Xld4enUboQiuOUvuaU-2PeLdlbSv_WDKBS6X95uhpYvrYPzjWVJidYPYvlC4GsbjE-xqJZ4kSFFO_U4',
    detailUrl: '/inventory/Used-2023-Ferrari-SF90_Stradale-Base-ZFF95NLA0P0292593',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ZFF68NHA9F0207042',
    slug: generateSlug(2015, 'Ferrari', '458-Spider'),
    year: 2015,
    make: 'Ferrari',
    model: '458 Spider',
    trim: 'Base',
    price: 419995,
    mileage: 3100,
    stock: '25851',
    vin: 'ZFF68NHA9F0207042',
    bodyType: 'Convertible',
    condition: 'used',
    engine: '4.5L V8 DI DOHC',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    fuelType: 'Gasoline',
    mpgCity: 13,
    mpgHighway: 17,
    exteriorColor: 'Red',
    interiorColor: 'Tan',
    doors: 2,
    description: '2015 Ferrari 458 Spider. Clean CARFAX.',
    features: ['Keyless Entry'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com/vehiclehistory/ar20/cFRD5kTKTJGhNfMeRj7KAJQONTWVV8De47w4ctrx6crI2aJjNqcbJjPCrlUYRXjRlRw62NpWwcwHjLr3sT4fgTs5E8CLE5iUB7c',
    detailUrl: '/inventory/Used-2015-Ferrari-458_Spider-Base-ZFF68NHA9F0207042',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'WP0AF2A93SS278605',
    slug: generateSlug(2025, 'Porsche', '911-GT3-RS'),
    year: 2025,
    make: 'Porsche',
    model: '911',
    trim: 'GT3 RS',
    price: 409995,
    mileage: 500,
    stock: '25781',
    vin: 'WP0AF2A93SS278605',
    bodyType: 'Coupe',
    condition: 'used',
    engine: '4.0L H6 DOHC 24V LEV3-LEV160 518hp',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    fuelType: 'Gasoline',
    mpgCity: 14,
    mpgHighway: 18,
    exteriorColor: 'Yellow',
    interiorColor: 'Black',
    doors: 2,
    description: '2025 Porsche 911 GT3 RS. Clean CARFAX.',
    features: ['Keyless Entry'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com/vehiclehistory/ar20/9vMQ0EKgfTFu-ODlwODhf6uIr0EjX1oEKPEI5xvEhO0eYLHdlsRP-J0e7glOl1k2tacIetFxHraQFTs1tjplpkX7n_J95v7PXC8',
    detailUrl: '/inventory/Used-2025-Porsche-911-GT3_RS-WP0AF2A93SS278605',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ZHWUA6ZX1PLA25297',
    slug: generateSlug(2023, 'Lamborghini', 'Huracan-STO'),
    year: 2023,
    make: 'Lamborghini',
    model: 'Huracan STO',
    trim: 'Base',
    price: 409995,
    mileage: 5400,
    stock: '25771',
    vin: 'ZHWUA6ZX1PLA25297',
    bodyType: 'Coupe',
    condition: 'used',
    engine: '5.2L V10',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    fuelType: 'Gasoline',
    mpgCity: 13,
    mpgHighway: 18,
    exteriorColor: 'Orange',
    interiorColor: 'Black',
    doors: 2,
    description: '2023 Lamborghini Huracan STO. Clean CARFAX.',
    features: ['Keyless Entry', 'AWD'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com/vehiclehistory/ar20/Pam2a1Ur1n6nm8yWN3xoBvDQJqe8yLzXcDN6y0td_JJq8Sds4HI-y5pLwqiuTkpkila0p6sBrINUSmX1oJcWnofkWO1M5kHcNAY',
    detailUrl: '/inventory/Used-2023-Lamborghini-Huracan_STO-Base-ZHWUA6ZX1PLA25297',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'ZHWUE4ZF4JLA04844',
    slug: generateSlug(2018, 'Lamborghini', 'Huracan-Performante'),
    year: 2018,
    make: 'Lamborghini',
    model: 'Huracan',
    trim: 'Performante',
    price: 389995,
    mileage: 6200,
    stock: '25306',
    vin: 'ZHWUE4ZF4JLA04844',
    bodyType: 'Coupe',
    condition: 'used',
    engine: '5.2L V10',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    fuelType: 'Gasoline',
    mpgCity: 13,
    mpgHighway: 18,
    exteriorColor: 'Green',
    interiorColor: 'Black',
    doors: 2,
    description: '2018 Lamborghini Huracan Performante. Clean CARFAX.',
    features: ['Keyless Entry', 'AWD'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com',
    detailUrl: '/inventory/Used-2018-Lamborghini-Huracan-Performante-ZHWUE4ZF4JLA04844',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'W1K6G6EB5MA081979',
    slug: generateSlug(2021, 'Mercedes-Benz', 'AMG-GT-63-S'),
    year: 2021,
    make: 'Mercedes-Benz',
    model: 'AMG GT',
    trim: 'GT 63 S',
    price: 379995,
    mileage: 7800,
    stock: '25679',
    vin: 'W1K6G6EB5MA081979',
    bodyType: 'Sedan',
    condition: 'used',
    engine: '4.0L V8 Twin Turbo',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    fuelType: 'Gasoline',
    mpgCity: 16,
    mpgHighway: 23,
    exteriorColor: 'Black',
    interiorColor: 'Red',
    doors: 4,
    description: '2021 Mercedes-Benz AMG GT 63 S. Clean CARFAX.',
    features: ['Keyless Entry', 'AWD', 'Twin Turbo'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com',
    detailUrl: '/inventory/Used-2021-Mercedes-Benz-AMG®_GT-GT_63_S-W1K6G6EB5MA081979',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SCA6X7RU9RUX00308',
    slug: generateSlug(2024, 'Rolls-Royce', 'Spectre'),
    year: 2024,
    make: 'Rolls-Royce',
    model: 'Spectre',
    trim: 'Base',
    price: 699995,
    mileage: 1200,
    stock: '25854',
    vin: 'SCA6X7RU9RUX00308',
    bodyType: 'Coupe',
    condition: 'used',
    engine: 'Electric',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    fuelType: 'Electric',
    mpgCity: 0,
    mpgHighway: 0,
    exteriorColor: 'Blue',
    interiorColor: 'Cream',
    doors: 2,
    description: '2024 Rolls-Royce Spectre. Clean CARFAX.',
    features: ['Keyless Entry', 'AWD', 'Electric'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com',
    detailUrl: '/inventory/Used-2024-Rolls-Royce-Spectre-Base-SCA6X7RU9RUX00308',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'WDDRJ7HA6CA008195',
    slug: generateSlug(2012, 'Mercedes-Benz', 'SLS-AMG'),
    year: 2012,
    make: 'Mercedes-Benz',
    model: 'SLS AMG',
    trim: 'Base',
    price: 279995,
    mileage: 8500,
    stock: '25730A',
    vin: 'WDDRJ7HA6CA008195',
    bodyType: 'Coupe',
    condition: 'used',
    engine: '6.2L V8',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    fuelType: 'Gasoline',
    mpgCity: 13,
    mpgHighway: 19,
    exteriorColor: 'Silver',
    interiorColor: 'Black',
    doors: 2,
    description: '2012 Mercedes-Benz SLS AMG. Clean CARFAX.',
    features: ['Keyless Entry', 'Gullwing Doors'],
    images: [
      'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    ],
    thumbnailUrl: 'https://images.app.ridemotive.com/oh17brmyjwscfcirhjkd8c9441ba',
    carfaxUrl: 'https://www.carfax.com',
    detailUrl: '/inventory/Used-2012-Mercedes-Benz-SLS_AMG®-Base-WDDRJ7HA6CA008195',
    location: 'Ewing, NJ',
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
];
